export type fileInformations = {
    id: number,
    name: String,
    type: String,
    status: unknown,
    visibility: String,
    drive_id: number,
    created_by: number,
    created_at: number,
    added_at: number,
    last_modified_at: number,
    last_modified_by: number,
    revised_at: number,
    updated_at: number,
    parent_id: number,
    size: number,
    mime_type: String,
    extension_type: String,
}